//THIS FILE IS AUTOGENERATED BY build.js, PLEASE DO NOT EDIT IT
  export async function handle(state, action) {
  if (!action.input || typeof action.input !== "object" || typeof action.input.function !== "string") {
    throw new ContractError("Invalid input");
  }

  const functionMap = {
"getEntries":require("./functions/getEntries.js"),
"getMetadata":require("./functions/getMetadata.js"),
"getQuestions":require("./functions/getQuestions.js"),
"setOwnEntry":require("./functions/setOwnEntry.js"),
"updateMetadata":require("./functions/updateMetadata.js"),
"updateQuestion":require("./functions/updateQuestion.js")
  };

  const selectedFunction = functionMap[action.input.function];
  if (!selectedFunction) {
    throw new ContractError(`Function '${action.input.function}' not found`);
  }

  try {
    return await selectedFunction(state, action, handle);
  } catch (error) {
    throw new ContractError(`Error executing function '${action.input.function}': ${ error.message }`);
  }
}
